service: express-serverless-ts

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline

package:
  individually: true
  patterns:
    - '!node_modules/aws-sdk/**'

custom:
  serverless-offline:
    httpPort: 3000
